# Grantmaker settings
foundation_name: Rural Community Solutions
foundation_tagline: founded by Sarah Benimana
grant_application_login: https://www.grantinterface.com/Common/LogOn.aspx?eqs=kw_123456_EXAMPLE

# Social media settings
# Enter the full profile URL (e.g., https://twitter.com/yourfoundation)
profile_twitter: https://twitter.com/examplefdn
profile_facebook: https://facebook.com/the-example-foundation
profile_instagram: https://www.instagram.com/ronanrm_/  # Updated to your Instagram
profile_github: https://github.com/rwandalibraryproject  # Change this to your project's GitHub repo URL

# Site settings
title: Rural Community Solutions  # Sets the browser tab title
description: >
  Rwanda is a small country in east Africa with 13.46 million people. Around 83% of the
  population live in rural areas, and 4 out of the 5 government public libraries in the country are
  located in Kigali, the capital city of Rwanda.

# Google settings
live: true  # Set to true if you're ready for search engines to index your site

# Jekyll settings
baseurl: ""  # Leave this blank for the root domain (e.g., https://rwandalibraryproject.github.io)
url: https://rwandalibraryproject.github.io  # The live GitHub Pages URL for your site
collections:
  featured-cards:
    output: true
sass:
  sass_dir: assets/css/_sass

# Build settings
markdown: kramdown
kramdown:
  input: GFM
exclude:
  - README.md
  - /images/photoshop-helpers
